name: Daily Air Quality & Pollen Collection

on:
  schedule:
    # Runs at 9:00 AM UTC (4 AM Central / 2 AM Arizona)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allows manual runs

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install requests
      
      - name: Run tracker
        env:
          AIRNOW_API_KEY: ${{ secrets.AIRNOW_API_KEY }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          python air_quality_pollen_tracker.py
      
      - name: Commit and push data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Daily data collection $(date +'%Y-%m-%d')" && git push)
